# Generated by Django 6.0.6 on 2026-06-21 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'departement',
                'verbose_name_plural': 'departements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('A', 'Autre')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=150)),
                ('date_embauche', models.DateField()),
                ('situation', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En conge'), ('suspendu', 'Suspendu'), ('sorti', 'Sorti')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='information_employees.departement')),
            ],
            options={
                'verbose_name': 'employe',
                'verbose_name_plural': 'employes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('prestation', 'Prestation'), ('consultance', 'Consultance')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('fichier_reference', models.CharField(blank=True, max_length=120)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='information_employees.employe')),
            ],
            options={
                'verbose_name': 'contrat',
                'verbose_name_plural': 'contrats',
                'ordering': ['-date_debut'],
            },
        ),
    ]
